[package]
name = "parser-c-macro"
version = "0.1.0"
authors = ["Tim Ryan <id@timryan.org>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.10.5", features = [ "full" ] }
quote = "0.3.10"